---
- hosts: all
  tasks:
    - ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'caddy version'
      ansible.builtin.command: /usr/local/bin/caddy version
      register: caddy_test_output
    - name: Output from 'caddy version'
      ansible.builtin.debug:
        msg: '{{ caddy_test_output.stdout }}'
