---
- name: Installing unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install in {{ caddy_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ caddy_install_dir }}'
  changed_when: false
  register: caddy_binary
- when: not caddy_binary.stat.exists
  block:
    - name: Downloading {{ caddy_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ caddy_url }}'
        dest: '{{ caddy_tmp_archive }}'
        mode: '644'
        checksum: '{{ caddy_checksum }}'
    - name: Mkdir {{ caddy_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ caddy_install_dir }}'
        state: directory
        mode: '755'
    - name: Unarchive {{ caddy_tmp_archive }} to {{ caddy_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ caddy_tmp_archive }}'
        dest: '{{ caddy_install_dir }}'
        creates: '{{ caddy_fq_exe }}'
  always:
    - name: Rm {{ caddy_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ caddy_tmp_archive }}'
        state: absent
- name: Link {{ caddy_fq_link }} to {{ caddy_fq_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ caddy_fq_exe }}'
    dest: '{{ caddy_fq_link }}'
    state: link
